### PR TITLE
Add optional semicolon

### LINKED ISSUE #14: grammar: optional semicolon
Although I've never seen it used in real projects, Elixir allows semicolon at the end of an expression.
I could for example be used to write 2 expressions on 1 line, like:

`a = 5; b = a + 10`

### PR DESCRIPTION
**Pull request by addcninblue**
Fixes #14.

I referenced Python's tree-sitter grammar, linked below, which did something similar.

https://github.com/tree-sitter/tree-sitter-python/blob/master/grammar.js#L442-L454

I included a few tests, but I'm unsure if there are any scenarios where it's valid that I missed, or where it's invalid that I included.

Thanks!

### CODE REVIEW

**Comment by Tuxified** [comment]
Hi,

Thanks for your PR, looks like a good start, I have one thing I'm unsure about: `; a = 1; b = 1` is also valid Elixir. In your branch it's also parsed without errors, but indicates there's a variable at the beginning:

```
source_file [0, 0] - [1, 0])
  variable [0, 0] - [0, 0])
  match [0, 2] - [0, 8])
    variable [0, 2] - [0, 3])
    number [0, 6] - [0, 7])
  match [0, 9] - [0, 14])
    variable [0, 9] - [0, 10])
    number [0, 13] - [0, 14])
```

How would you like to deal with this? 
1) Merge current version & create new issue
2) Try to address it in this PR (which sparks a new question: what / how this be addressed)

On the question how to address this, it might help to look at Ruby's version, as Ruby also has an optional semicolon to end statements/expressions

**Comment by addcninblue** [comment]
I've tried to debug this, but I can't figure out why it's happening :(. If I change the `_identifier` regex to instead just be a string (ie. `"a"`), and use the test case `; a = 1 ;`, the bug goes away (and the parse fails). If I instead use `_identifier = /a/`, the bug comes back.

Is there any chance this is a tree-sitter bug? Or am I misunderstanding the use of the regex here?

**Comment by addcninblue** [comment]
Running with `--debug`, I see that there was indeed an error logged:

```
select_smaller_error symbol:source_file, over_symbol:ERROR
```

It looks like tree-sitter tried to resolve the error by looking at various parse paths and choosing the one with a smaller error. This would mean that this parsing is the intended outcome, since there was an error but it picked a result that was mostly reasonable?

**Comment by addcninblue** [comment]
Apologies in advance for the spam! I went ahead and tried implementing newline detection, using "liberal amounts of inspiration" from the python tree-sitter repo. You can see the commit at my fork: https://github.com/addcninblue/tree-sitter-elixir/commit/7c54e154bf98acafd88073257ca7d0709481ef7d

All tests are passing except one: 

```
  1. Struct error with string key:
    (source_file (ERROR (struct (alias) (MISSING "}")) (expr_op (string) (ERROR) (number)))) (number)) (ERROR))
```

Hopefully work on these two expression terminators can help start the work for other issues!

**Comment by Tuxified** [comment]
Looks good, thanks! Don't get hung op on the tests for non valid Elixir. The point is to prove the parser will return _some_ error, doesn't have to be those specifically :D

**Pull request merged**
